### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by one-aalam** [one-aalam/stayin#1]
Stayin-micro
- [x] Use micro-joi for payload validation
- [ ] Use joi-password-complexity
- [ ] Remove lodash - Prefer ES6
